import = ["~/.config/alacritty/themes/alabaster_dark.toml"]

[env]
TERM = "xterm-256color"

[window.padding]
x = 2
y = 2

[font]
size = 18.0

[font.normal]
family = "Iosevka"
style = "Pango"

[font.italic]
family = "Iosevka"
style = "Pango"

[font.bold]
family = "Iosevka"
style = "Pango"

[font.offset]
x = -1
y = -1


