import = ["~/.config/alacritty/themes/alabaster_dark.toml"]

[env]
TERM = "xterm-256color"

[colors.primary]
background = "#181818"

[window.padding]
x = 2
y = 2

[font]
size = 14.0

[font.normal]
family = "Iosevka"
style = "Pango"

[font.italic]
family = "Iosevka"
style = "Pango"

[font.bold]
family = "Iosevka"
style = "Pango"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
