[env]
TERM = "xterm-256color"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[window]
title = "Alacritty"

[window.padding]
x = 6
y = 6

[font]
size = 14.0

[font.normal]
# family = "Source Code Pro for Powerline"
# family = "Roboto Mono for Powerline"
# family = "Inconsolata for Powerline"
style = "Regular"

[font.offset]
x = -1
y = -1
