-- require("colorizer").setup {
--   filetypes = { "*" },
--   user_default_options = {
--     RGB = true,
--     RRGGBB = true,
--     names = true,
--     RRGGBBAA = false,
--     AARRGGBB = true,
--     rgb_fn = false,
--     hsl_fn = false,
--     css = false,
--     css_fn = false,
--     tailwind = false,
--     mode = "virtualtext",
--     virtualtext_inline = false,
--     virtualtext = "■",
--     virtualtext_mode = "foreground",
--     always_update = false
--   },
--   buftypes = {},
-- }
